name: Selenium Testing with Pytest

on:
    workflow_dispatch:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    test:
        timeout-minutes: 60
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11.9"

            - name: Install Dependencies
              run: |
                  python -m venv .venv
                  .\.venv\Scripts\activate
                  pip install -r requirements.txt

            - name: Set Up ChromeDriver for Selenium
              run: |
                  choco install googlechrome
                  choco install chromedriver

            - name: Run Selenium Tests with Pytest
              continue-on-error: true
              run: |
                  .\.venv\Scripts\activate
                  pytest -v --browser=chrome --headless=true -n 2 --alluredir=allure-results

            - name: Install Allure CLI
              run: |
                  curl -L -o allure.zip https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.zip
                  powershell -Command "Expand-Archive allure.zip -DestinationPath ."
                  echo "${{ github.workspace }}\\allure-2.34.1\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

            - name: Verify Allure Installation
              run: allure --version

            - name: Generate Allure Report
              run: allure generate allure-results -o allure-report --clean

            - name: List Allure Report Directory
              run: dir allure-report

            - name: Upload Allure Report
              uses: actions/upload-artifact@v4
              with:
                  name: allure-report
                  path: allure-report/
                  retention-days: 30

            - name: Publish Allure Report to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: allure-report
